org: devdeepnarayan
app: loanmantratestapi
service: loanmantra-server

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  stage: prod

  httpApi:
    cors:
      allowedOrigins:
        - https://main.d3a7mju9zni36v.amplifyapp.com
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowCredentials: false
      maxAge: 86400

  environment:
    NODE_ENV: production
    DYNAMODB_TABLE_NAME: LoanSubmissions
    ALLOWED_ORIGINS: https://main.d3a7mju9zni36v.amplifyapp.com

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:Query
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/LoanSubmissions

functions:
  createSubmission:
    handler: index.handler
    events:
      - httpApi:
          path: /api/submissions
          method: POST

  uploadDocs:
    handler: index.handler
    events:
      - httpApi:
          path: /api/submissions/{id}/upload
          method: POST

  health:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: GET